#pragma once

namespace MGDF
{

/**
 * Various error codes returned by the MGDF api
 */
enum MGDFError {
	MGDF_OK = 0,
	MGDF_ERR_ERROR_ALLOCATING_BUFFER = 1,
	MGDF_ERR_NO_FREE_SOURCES = 2,
	MGDF_ERR_VORBIS_LIB_LOAD_FAILED = 3,
	MGDF_ERR_INVALID_FORMAT = 4,
	MGDF_ERR_INVALID_ARCHIVE = 5,
	MGDF_ERR_INVALID_ARCHIVE_FILE = 6,
	MGDF_ERR_INVALID_FILE = 7,
	MGDF_ERR_NO_PENDING_SAVE = 8,
	MGDF_ERR_INVALID_SAVE_NAME = 9,
	MGDF_ERR_ARCHIVE_FILE_TOO_LARGE = 10,
	MGDF_ERR_FILE_IN_USE = 11,
	MGDF_ERR_BUFFER_TOO_SMALL = 12,
	MGDF_ERR_FATAL = 13,
	MGDF_ERR_IS_FOLDER = 14,
	MGDF_ERR_GPU_TIMER_UNSUPPORTED = 15,
	MGDF_ERR_INVALID_TIMER_NAME = 16
};

}