#pragma once

#include <MGDF/MGDFVersion.hpp>
#include <MGDF/MGDFSound.hpp>
#include <MGDF/MGDFSoundStream.hpp>
#include <MGDF/MGDFSoundManager.hpp>
#include <MGDF/MGDFGame.hpp>
#include <MGDF/MGDFInputManager.hpp>
#include <MGDF/MGDFList.hpp>
#include <MGDF/MGDFLogger.hpp>
#include <MGDF/MGDFModule.hpp>
#include <MGDF/MGDFParameterManager.hpp>
#include <MGDF/MGDFSystem.hpp>
#include <MGDF/MGDFCustomArchiveHandlers.hpp>
#include <MGDF/MGDFVirtualFileSystem.hpp>
#include <MGDF/MGDFStatisticsManager.hpp>
#include <MGDF/MGDFGraphicsManager.hpp>
#include <MGDF/MGDFError.hpp>
#include <MGDF/MGDFErrorHandler.hpp>
#include <MGDF/MGDFTimer.hpp>