<?xml version="1.0" encoding="utf-8"?>
<Database Name="GameSource" Class="GameSourceRepository" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="ConnectionString" ConnectionString="Data Source=(local);Persist Security Info=True;User ID=dev" Provider="System.Data.SqlClient" />
  <Table Name="dbo.mgdf_gamefragments" Member="GameFragments">
    <Type Name="GameFragment">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameDataId" Storage="_GameFragmentFile" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DeveloperId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="false" />
      <Column Name="Md5Hash" Storage="_SHA1Hash" Type="System.String" CanBeNull="true" />
      <Column Name="GameVersionId" Type="System.Guid" CanBeNull="false" />
      <Column Name="PublishOnComplete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" CanBeNull="false" />
      <Association Name="GameFragment_GameVersion" Member="GameVersion" ThisKey="GameVersionId" OtherKey="Id" Type="GameVersion" Cardinality="One" />
      <Association Name="Developer_GameFragment" Member="Developer" ThisKey="DeveloperId" OtherKey="Id" Type="Developer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.mgdf_developers" Member="Developers">
    <Type Name="Developer">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Homepage" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DeveloperKey" Storage="_PublicKey" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SecretKey" Storage="_PrivateKey" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Uid" Type="System.String" CanBeNull="false" />
      <Column Name="Custom" Type="System.String" CanBeNull="false" />
      <Association Name="Developer_GameFragment" Member="GameFragments" ThisKey="Id" OtherKey="DeveloperId" Type="GameFragment" />
      <Association Name="Developer_Game" Member="Games" ThisKey="Id" OtherKey="DeveloperId" Type="Game" />
    </Type>
  </Table>
  <Table Name="dbo.mgdf_users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Custom" Type="System.String" CanBeNull="false" />
      <Association Name="User_UserGame" Member="UserGames" ThisKey="Id" OtherKey="UserId" Type="UserGame" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.mgdf_games" Member="Games">
    <Type Name="Game">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Uid" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Homepage" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DeveloperId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="false" />
      <Column Name="InterfaceVersion" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="RequiresAuthentication" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Game_UserGame" Member="UserGames" ThisKey="Id" OtherKey="GameId" Type="UserGame" Cardinality="One" />
      <Association Name="Game_GameVersion" Member="GameVersions" ThisKey="Id" OtherKey="GameId" Type="GameVersion" />
      <Association Name="Developer_Game" Member="Developer" ThisKey="DeveloperId" OtherKey="Id" Type="Developer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.mgdf_usergames" Member="UserGames">
    <Type Name="UserGame">
      <Column Name="GameId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_UserGame" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Game_UserGame" Member="Game" ThisKey="GameId" OtherKey="Id" Type="Game" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.mgdf_gameversions" Member="GameVersions">
    <Type Name="GameVersion">
      <Column Name="Version" Type="System.String" DbType="varchar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IsUpdate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UpdateMinVersion" Type="System.String" DbType="varchar(255) NOT NULL" CanBeNull="true" />
      <Column Name="UpdateMaxVersion" Type="System.String" DbType="varchar(255) NOT NULL" CanBeNull="true" />
      <Column Name="GameDataId" Storage="_GameFile" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="Description" Storage="_UpdateDescription" Type="System.String" CanBeNull="true" />
      <Column Name="Md5Hash" Storage="_SHA1Hash" Type="System.String" CanBeNull="true" />
      <Column Name="GameId" Type="System.Guid" CanBeNull="false" />
      <Column Name="Id" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Published" Type="System.Boolean" CanBeNull="false" />
      <Association Name="Game_GameVersion" Member="Game" ThisKey="GameId" OtherKey="Id" Type="Game" IsForeignKey="true" />
      <Association Name="GameFragment_GameVersion" Member="GameFragment" ThisKey="Id" OtherKey="GameVersionId" Type="GameFragment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.mgdf_defaultfileservergamedata" Member="DefaultFileServerGameDatas">
    <Type Name="DefaultFileServerGameData">
      <Column Name="GameFile" Storage="_GameFragmentFile" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.mgdf_amazons3fileservergamedata" Member="AmazonS3FileServerGameDatas">
    <Type Name="AmazonS3FileServerGameData">
      <Column Name="Id" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UploadID" Type="System.String" CanBeNull="false" />
      <Column Name="Key" Type="System.String" CanBeNull="false" />
      <Column Name="NextPartIndex" Type="System.Int32" CanBeNull="false" />
      <Association Name="AmazonS3FileServerGameData_AmazonS3UploadPart" Member="AmazonS3UploadParts" ThisKey="Id" OtherKey="GameDataId" Type="AmazonS3UploadPart" />
    </Type>
  </Table>
  <Table Name="dbo.mgdf_amazons3uploadpart" Member="AmazonS3UploadParts">
    <Type Name="AmazonS3UploadPart">
      <Column Name="GameDataId" Type="System.Guid" CanBeNull="false" />
      <Column Name="ETag" Type="System.String" CanBeNull="false" />
      <Column Name="PartIndex" Type="System.Int32" CanBeNull="false" />
      <Column Name="Id" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AmazonS3FileServerGameData_AmazonS3UploadPart" Member="AmazonS3FileServerGameData" ThisKey="GameDataId" OtherKey="Id" Type="AmazonS3FileServerGameData" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.mgdf_cnonce" Member="CNonces">
    <Type Name="CNonce">
      <Column Name="Id" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Expires" Type="System.DateTime" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.mgdf_queuedfiledelete" Member="QueuedFileDeletes">
    <Type Name="QueuedFileDelete">
      <Column Member="FileName" Type="System.String" CanBeNull="false" />
      <Column Name="Id" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>